// Generated by scripts/update-component-provenance.mjs. Do not edit by hand.

type ComponentProvenance = {
  name: string
  href: string
  evidence: string
}

const componentProvenance = {
  "liquid-glass-navbar": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com",
      "evidence": "session-watcher-website/components/HomeHeader.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app",
      "evidence": "moorline-website/src/components/marketing/MoorlineHeader.tsx"
    }
  ],
  "blue-cta-button": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com",
      "evidence": "session-watcher-website/components/HomeHeader.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app",
      "evidence": "moorline-website/src/components/marketing/MoorlineHeader.tsx"
    }
  ]
} as const satisfies Record<string, readonly ComponentProvenance[]>

function getComponentProvenance(slug: string): readonly ComponentProvenance[] {
  return componentProvenance[slug as keyof typeof componentProvenance] ?? []
}

export { componentProvenance, getComponentProvenance }
export type { ComponentProvenance }
