// Generated by scripts/update-component-provenance.mjs. Do not edit by hand.

type ComponentProvenance = {
  name: string
  href: string
  iconSrc?: string
  evidence: string
}

const componentProvenance = {
  "liquid-glass-navbar": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/HomeHeader.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/MoorlineHeader.tsx"
    }
  ],
  "blue-cta-button": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/HomeHeader.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/MoorlineHeader.tsx"
    }
  ],
  "gradient-faq": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/cuicui/GradientFAQ.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/cuicui/GradientFAQ.tsx"
    }
  ],
  "scroll-reveal": [
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/Reveal.tsx"
    }
  ],
  "terminal-command": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/BrewCommand.tsx"
    }
  ],
  "macbook-mockup": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/MacbookPreview.tsx"
    }
  ],
  "sticky-product-cta": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/StickyBuyBar.tsx"
    }
  ],
  "social-proof": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/SocialProof.tsx"
    }
  ],
  "testimonials-grid": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/Testimonials.tsx"
    }
  ],
  "whats-new-card": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/WhatsNewCard.tsx"
    }
  ],
  "release-history-dialog": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/ReleaseHistoryDialog.tsx"
    }
  ],
  "single-pricing-card": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/ToolPricingCard.tsx"
    }
  ],
  "pricing-block": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/__tests__/ai-coding-tool-usage.test.mjs"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/PricingTrust.tsx"
    }
  ],
  "provider-orbit": [
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/ProviderOrbit.tsx"
    }
  ],
  "morphing-download-icon": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/MorphingDownloadIcon.tsx"
    }
  ],
  "founder-note": [
    {
      "name": "SessionWatcher",
      "href": "https://sessionwatcher.com?ref=ui.starck.studio",
      "iconSrc": "/products/sessionwatcher.png",
      "evidence": "session-watcher-website/components/FounderNote.tsx"
    },
    {
      "name": "Moorline",
      "href": "https://moorline.app?ref=ui.starck.studio",
      "iconSrc": "/products/moorline.png",
      "evidence": "moorline-website/src/components/marketing/Closing.tsx"
    }
  ]
} as const satisfies Record<string, readonly ComponentProvenance[]>

function getComponentProvenance(slug: string): readonly ComponentProvenance[] {
  return componentProvenance[slug as keyof typeof componentProvenance] ?? []
}

export { componentProvenance, getComponentProvenance }
export type { ComponentProvenance }
